### ISSUE TITLE
GitBookでの公開

### ISSUE THREAD

**Issue by mizunashi-mana** [Kinokkory/wiwinwlh-jp#1]
素晴らしいプロジェクトありがとうございます。
このドキュメントをGitBook化して管理したいと考えているのですが、大丈夫でしょうか？

実は承諾とるの忘れて公開してしまって、
https://github.com/mizunashi-mana/wiwinwlh-jp
こんな感じになっています。

事後承諾の形になって申し訳有りません。

Pull Request送ることも考えたのですが、GitBookの管理を押しつけるのもお門違いな気がしたので。
2.3で色々重要な変更が追加されているので、細々と2.3の翻訳も追加していきたいと思っています。

パブリックドメインにはなっていますが、@KinokkoryさんのThxメッセージも入れようと考えています。

何かご要望があれば、承りますので返信よろしくお願いします。

**Comment by shiatsumat** [comment]
Mizunashi Mana さま

了解です。よりよい翻訳づくりのため、頑張ってください。

松下 祐介

2016年7月24日 7:01 Mizunashi Mana notifications@github.com:

**Comment by mizunashi-mana** [comment]
@Kinokkory ありがとうございます
